In [1]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv("house.csv")

In [6]:
data.head()

   beds  baths  size size_units  lot_size lot_size_units  zip_code    price
0     3    2.5  2590       sqft   6000.00           sqft     98144   795000
1     4    2.0  2240       sqft      0.31           acre     98106   915000
2     4    3.0  2040       sqft   3783.00           sqft     98107   950000
3     4    3.0  3800       sqft   5175.00           sqft     98199  1950000
4     2    2.0  1042       sqft       NaN            NaN     98102   950000

In [7]:
data.shape

(2521, 8)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2521 entries, 0 to 2520
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   beds            2521 non-null   int64
 1   baths           2521 non-null   float64
 2   size            2521 non-null   int64
 3   size_units      2521 non-null   object
 4   lot_size        2097 non-null   float64
 5   lot_size_units  2097 non-null   object
 6   zip_code        2521 non-null   int64
 7   price           2521 non-null   int64
dtypes: float64(2), int64(4), object(2)
memory usage: 157.7+ KB

In [9]:

for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

3     818
2     686
4     506
1     311
5     156
6      25
7       9
9       6
8       2
15      1
14      1
Name: beds, dtype: int64
********************
2.0    767
1.0    603
2.5    377
3.0    251
3.5    215
1.5    177
4.0     48
4.5     26
5.0     24
5.5     15
6.0      8
7.0      5
6.5      2
8.5      1
0.5      1
9.0      1
Name: baths, dtype: int64
********************
2080    14
1460    14
1540    14
1660    14
1550    13
        ..
3488     1
1742     1
4018     1
1759     1
1301     1
Name: size, Length: 1014, dtype: int64
********************
sqft    2520
3          1
Name: size_units, dtype: int64
********************
5000.0    75
4000.0    59
6000.0    46
1.0       32
4800.0    20
          ..
6710.0     1
802.0      1
7548.0     1
2388.0     1
4887.0     1
Name: lot_size, Length: 1134, dtype: int64
********************
sqft    1817
acre     279
3          1
Name: lot_size_units, dtype: int64
********************
98103    214
98115    209
98117    189
98122    138
98144    134
98118    120
98125    107
98126    102
98116    100
98107    100
98199     97
98106     93
98119     89
98105     88
98102     79
98136     77
98109     74
98133     73
98121     73
98112     69
98178     60
98146     56
98168     51
98108     45
98177     35
98101     28
98104     17
98164      2
98188      1
3          1
Name: zip_code, dtype: int64
********************
895000     189
750000      31
700000      29
850000      28
900000      24
          ...
1420000      1
497000       1
659950       1
325100       1
3            1
Name: price, Length: 838, dtype: int64
********************

In [10]:
data.isna().sum()

beds                0
baths               0
size                0
size_units          0
lot_size          424
lot_size_units    424
zip_code            0
price               0
dtype: int64

In [11]:

data.drop(columns=['lot_size','lot_size_units'],inplace=True)

In [12]:
data.describe()

              beds        baths          size      zip_code         price
count  2521.000000  2521.000000   2521.000000   2521.000000  2.521000e+03
mean      2.877033     2.172154   1758.519238  98085.069814  9.556964e+05
std       1.247518     1.004511    922.206681   1954.365945  8.657586e+05
min       1.000000     0.500000      3.000000      3.000000  3.000000e+00
25%       2.000000     1.500000   1081.000000  98108.000000  6.250000e+05
50%       3.000000     2.000000   1580.000000  98117.000000  8.499500e+05
75%       4.000000     2.500000   2270.000000  98126.000000  1.062500e+06
max      15.000000     9.000000  11010.000000  98199.000000  2.500000e+07

In [13]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2521 entries, 0 to 2520
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   beds        2521 non-null   int64
 1   baths       2521 non-null   float64
 2   size        2521 non-null   int64
 3   size_units  2521 non-null   object
 4   zip_code    2521 non-null   int64
 5   price       2521 non-null   int64
dtypes: float64(1), int64(4), object(1)
memory usage: 118.3+ KB

In [14]:
data['beds'].value_counts()

3     818
2     686
4     506
1     311
5     156
6      25
7       9
9       6
8       2
15      1
14      1
Name: beds, dtype: int64

In [15]:

data.head()

   beds  baths  size size_units  zip_code    price
0     3    2.5  2590       sqft     98144   795000
1     4    2.0  2240       sqft     98106   915000
2     4    3.0  2040       sqft     98107   950000
3     4    3.0  3800       sqft     98199  1950000
4     2    2.0  1042       sqft     98102   950000

In [16]:
data['price_per_sqft'] = data['price'] * 100000 / data['size']

In [17]:
data['price_per_sqft']

0       3.069498e+07
1       4.084821e+07
2       4.656863e+07
3       5.131579e+07
4       9.117083e+07
            ...
2516    1.603943e+07
2517    6.438849e+07
2518    3.033898e+07
2519    2.973422e+07
2520    6.879324e+07
Name: price_per_sqft, Length: 2521, dtype: float64

In [18]:

data.describe()

,beds,baths,size,zip_code,price,price_per_sqft
count,2521.000000,2521.000000,2521.000000,2521.000000,2.521000e+03,2.521000e+03
mean,2.877033,2.172154,1758.519238,98085.069814,9.556964e+05,5.866161e+07
std,1.247518,1.004511,922.206681,1954.365945,8.657586e+05,7.547902e+07
min,1.000000,0.500000,3.000000,3.000000,3.000000e+00,1.000000e+05
25%,2.000000,1.500000,1081.000000,98108.000000,6.250000e+05,4.357798e+07
50%,3.000000,2.000000,1580.000000,98117.000000,8.499500e+05,5.462963e+07
75%,4.000000,2.500000,2270.000000,98126.000000,1.062500e+06,6.603774e+07
max,15.000000,9.000000,11010.000000,98199.000000,2.500000e+07,3.424658e+09

In [19]:

data.shape

(2521, 7)

In [20]:
data

      beds  baths  size size_units  zip_code    price  price_per_sqft
0        3    2.5  2590       sqft     98144   795000    3.069498e+07
1        4    2.0  2240       sqft     98106   915000    4.084821e+07
2        4    3.0  2040       sqft     98107   950000    4.656863e+07
3        4    3.0  3800       sqft     98199  1950000    5.131579e+07
4        2    2.0  1042       sqft     98102   950000    9.117083e+07
...    ...    ...   ...        ...       ...      ...             ...
2516     5    4.5  5580       sqft     98146   895000    1.603943e+07
2517     3    2.5  1390       sqft     98126   895000    6.438849e+07
2518     3    2.5  2950       sqft     98118   895000    3.033898e+07
2519     5    5.0  3010       sqft     98115   895000    2.973422e+07
2520     3    2.0  1301       sqft     98103   895000    6.879324e+07

[2521 rows x 7 columns]

In [21]:

data.drop(columns=['size_units'],inplace=True)

In [22]:
data.drop(columns=['price_per_sqft'],inplace=True)

In [23]:
data.head()

   beds  baths  size  zip_code    price
0     3    2.5  2590     98144   795000
1     4    2.0  2240     98106   915000
2     4    3.0  2040     98107   950000
3     4    3.0  3800     98199  1950000
4     2    2.0  1042     98102   950000

In [24]:

data.to_csv("final_dataset.csv")

In [25]:

X=data.drop(columns=['price'])
y=data['price']

In [26]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [28]:

print(X_train.shape)
print(y_train.shape)

(2016, 4)
(2016,)

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
import pandas as pd

# Example data setup (replace with your data)
# X = pd.DataFrame(...)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Automatically detect numeric and categorical features
numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X_train.select_dtypes(include=['object', 'category']).columns.tolist()

# Verify the detected features
print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

# Define the column transformer with OneHotEncoder and StandardScaler
preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())]), numeric_features),
        
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

# Create a pipeline with the preprocessor and a classifier
pipe = Pipeline(steps=[('preprocessor', preprocessor),
                       ('classifier', LogisticRegression())])

# Fit the pipeline on the training data
pipe.fit(X_train, y_train)

# Predict on the test data
y_pred = pipe.predict(X_test)

Numeric features: ['beds', 'baths', 'size', 'zip_code']
Categorical features: []

C:\Users\Nikita\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [69]:
from sklearn.ensemble import RandomForestRegressor
pipe = Pipeline(steps=[('preprocessor', preprocessor),
                       ('model', RandomForestRegressor(n_estimators=100, random_state=0))])

# Fit the pipeline on the training data
pipe.fit(X_train, y_train)

# Predict on the test data
y_pred = pipe.predict(X_test)

# Display predictions
print("Predicted prices:", y_pred)

ValueError: Found unknown categories [3] in column 0 during transform

In [62]:
r2_score(y_test,y_pred)

0.03838207311240083

In [63]:

y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.03838207311240083

In [64]:
pipe = Pipeline(steps=[('preprocessor', preprocessor),
                       ('model', LinearRegression())])

# Fit the pipeline on the training data
pipe.fit(X_train, y_train)

# Predict on the test data
y_pred = pipe.predict(X_test)

# Display predictions
print("Predicted prices:", y_pred)

Predicted prices: [8.64412908e+05 1.56168017e+06 1.13868187e+06 6.19522450e+05
 8.22038564e+05 1.19474112e+06 1.24246738e+06 1.49307992e+06
 1.53686488e+06 1.00751934e+06 8.10708410e+05 6.09108372e+05
 6.64831833e+05 7.97573901e+05 5.63913648e+05 9.75445053e+05
 1.05123550e+06 5.27075696e+05 1.02534962e+06 1.02669400e+06
 1.00921340e+06 1.11024861e+06 1.24502890e+06 7.04423164e+05
 9.84901612e+05 1.09581199e+06 2.36614986e+06 1.06906912e+06
 1.73368826e+06 5.88876498e+05 6.20580608e+05 1.27334565e+06
 6.25918397e+05 7.77486810e+05 1.12075100e+06 9.36337966e+05
 9.55940863e+05 6.11150578e+05 9.52074015e+05 1.57892750e+06
 1.56590251e+06 8.42347323e+05 8.25567370e+05 6.06878805e+05
 6.01541146e+05 5.21949948e+05 1.27877099e+06 9.33654458e+05
 7.67349198e+05 8.44188097e+05 1.08868545e+06 9.16251641e+05
 7.27620197e+05 4.95911142e+05 5.92682593e+05 4.63686812e+05
 1.10829819e+06 7.67377524e+05 9.78647881e+05 9.78121498e+05
 9.87622120e+05 9.93322944e+05 7.44290655e+05 7.58397889e+05
 6.31708430e+05 1.43592877e+06 7.60885227e+05 1.37810473e+06
 1.82460070e+06 2.23383137e+05 1.24951605e+06 9.04304332e+05
 5.61346727e+05 8.78847739e+05 1.10836878e+06 4.39993260e+05
 9.09459385e+05 1.33725052e+06 1.18224432e+06 6.50683410e+05
 5.62839490e+05 5.32969861e+05 7.58019884e+05 1.17127548e+06
 1.43385310e+06 1.55705184e+06 7.06478543e+05 7.19834722e+05
 8.89882805e+05 9.25192475e+05 7.31293015e+05 8.12199375e+05
 6.94228006e+05 2.02343956e+06 6.77836842e+05 9.11234699e+05
 1.51006665e+06 1.13076920e+06 1.38734579e+06 1.02125994e+06
 6.45699742e+05 9.04415653e+05 1.00251107e+06 8.09690904e+05
 8.77386767e+05 7.48185190e+05 5.50606748e+05 9.35852052e+05
 1.22990165e+06 6.41484674e+05 4.88226563e+05 1.58889637e+06
 1.05826124e+06 1.09641089e+06 2.24317023e+06 8.35249061e+05
 2.20056566e+08 1.04185839e+06 1.36307994e+06 1.19606265e+06
 9.59725903e+05 4.71746829e+05 1.58939468e+06 6.65566967e+05
 1.11303617e+06 4.69255896e+05 1.01700949e+06 9.47419924e+05
 1.13794686e+06 1.68914537e+06 9.77640132e+05 6.99662195e+05
 5.39670653e+05 9.67880525e+05 6.31468145e+05 9.64774000e+05
 7.60040826e+05 7.49177968e+05 1.46173687e+06 1.01143681e+06
 4.47129293e+05 8.26707625e+05 5.14035611e+05 5.41912493e+05
 1.05588959e+06 8.02760537e+05 1.00862079e+06 9.28995106e+05
 1.36743090e+06 1.13138847e+06 1.33430206e+06 8.54890123e+05
 8.66405655e+05 1.01520405e+06 6.63823314e+05 1.03912184e+06
 4.68759507e+05 6.88990163e+05 9.28685047e+05 1.54836369e+06
 1.13725957e+06 5.46864056e+05 9.57505379e+05 1.52124295e+06
 2.03042470e+06 1.04015521e+06 4.26801198e+05 1.60457481e+06
 8.43724347e+05 1.16294968e+06 6.38390474e+05 8.52414160e+05
 1.15304606e+06 1.07502969e+06 1.37860364e+06 1.15836687e+06
 5.32950526e+05 1.04628555e+06 9.29870527e+05 8.10436386e+05
 7.68577897e+05 7.57338883e+05 1.43016616e+06 8.31295489e+05
 1.45720925e+06 8.49737845e+05 5.47236978e+05 1.10561121e+06
 4.27397406e+05 6.55651076e+05 1.13068628e+06 1.19648298e+06
 9.76953557e+05 6.92026814e+05 1.06728589e+06 7.88364638e+05
 8.35265832e+05 1.05456729e+06 9.67272815e+05 8.15435791e+05
 1.05528786e+06 1.00583041e+06 6.28016224e+05 1.63018351e+06
 8.99755400e+05 1.18800315e+06 1.16977912e+06 1.10277060e+06
 1.31744701e+06 7.53242784e+05 8.54760180e+05 1.44077641e+06
 1.17853264e+06 6.88537070e+05 5.38899542e+05 1.33699963e+06
 8.24236210e+05 1.07999101e+06 4.58283644e+05 1.41915313e+06
 6.18104775e+05 1.11256092e+06 1.05256928e+06 7.17354574e+05
 9.57505379e+05 4.85188881e+05 7.45220671e+05 2.32966450e+06
 8.32564786e+05 1.45428191e+06 4.68764002e+05 1.39648440e+06
 1.02671501e+06 5.03161377e+05 5.92272667e+05 7.94358618e+05
 7.75098390e+05 1.10745643e+06 7.57595754e+05 6.10852025e+05
 1.02371716e+06 1.48568940e+06 1.07670964e+06 6.67830840e+05
 9.92658764e+05 6.38916086e+05 9.44365344e+05 7.12703181e+05
 1.37038117e+06 5.51218876e+05 1.34499522e+06 1.03352982e+06
 6.66162275e+05 7.88951215e+05 1.23872746e+06 7.82639087e+05
 6.14045992e+05 5.24802832e+05 8.18341863e+05 1.09291824e+06
 7.13549379e+05 1.34666533e+06 6.08815032e+05 5.47509002e+05
 1.23382348e+06 4.66044208e+05 7.97960714e+05 1.66849039e+06
 4.01305546e+05 1.59284301e+06 5.11271753e+05 8.48315675e+05
 9.78453509e+05 9.53208030e+05 7.13377171e+05 8.03718056e+05
 1.08020754e+06 1.12628372e+06 7.21917576e+05 1.11650928e+06
 4.69835463e+05 7.79845876e+05 1.47712940e+06 1.39103614e+06
 7.89151620e+05 2.37060702e+06 3.50110550e+05 7.68105338e+05
 7.71466301e+05 1.36728612e+06 8.88314955e+05 7.84840198e+05
 7.51677762e+05 1.20187369e+06 9.12294344e+05 8.92030039e+05
 8.46063230e+05 7.52491321e+05 8.44033427e+05 8.77514859e+05
 1.42011604e+06 5.31258129e+05 1.08486266e+06 9.57903697e+05
 6.76599206e+05 6.74276246e+05 1.11597057e+06 5.95944637e+05
 6.73974996e+05 1.37343028e+06 1.39757353e+06 1.05431114e+06
 2.66677642e+06 4.77966972e+05 6.56428296e+05 1.14361590e+06
 8.42644078e+05 1.27532954e+06 1.59910277e+06 5.18068765e+05
 6.27784669e+05 9.41324915e+05 5.47286437e+05 1.02245415e+06
 8.80370495e+05 7.05885933e+05 4.36448467e+06 9.52050054e+05
 9.60452050e+05 5.86606332e+05 9.93294800e+05 6.97708119e+05
 1.26662732e+06 6.93523172e+05 1.15068935e+06 4.61496229e+05
 9.13255515e+05 6.46920481e+05 5.26629667e+05 5.15747473e+05
 1.55385404e+06 1.78368995e+06 8.21378517e+05 9.47476394e+05
 4.72148795e+05 8.76869062e+05 5.66076806e+05 1.23078138e+06
 7.91025082e+05 5.48207723e+05 1.33205315e+06 7.10667908e+05
 7.82563099e+05 7.40725743e+05 1.22156421e+06 1.36835309e+06
 4.67269442e+05 5.86935008e+05 6.63137818e+05 4.80610778e+05
 8.57035482e+05 5.17422201e+05 6.56170395e+05 1.01058072e+06
 1.98863931e+06 7.58397889e+05 5.85914624e+05 1.26464703e+06
 8.52746301e+05 2.77518700e+06 1.49313105e+06 5.54377507e+05
 6.49448471e+05 7.89756685e+05 7.05663238e+05 1.17156522e+06
 1.35152085e+06 1.33437098e+06 7.72606556e+05 1.52017773e+06
 7.88265720e+05 1.18076383e+06 1.72923817e+06 5.67221556e+05
 1.89899715e+06 5.25684550e+05 1.41887944e+06 9.58843601e+05
 1.05565989e+06 5.24017782e+05 1.12379562e+06 4.85361989e+05
 5.13132760e+05 1.71984160e+06 7.34534696e+05 5.46938426e+05
 1.21283644e+06 7.19368453e+05 6.35823683e+05 4.81927554e+05
 1.14442676e+06 1.32971067e+06 8.35076852e+05 4.95185892e+05
 1.73324120e+06 5.51688737e+05 1.08722448e+06 8.72968467e+05
 9.39265302e+05 9.61128607e+05 5.53505680e+05 7.31750423e+05
 1.01084753e+06 9.98644914e+05 8.64444699e+05 4.69436194e+05
 8.54518280e+05 6.25993484e+05 7.32114485e+05 8.63674489e+05
 8.52226981e+05 8.38092371e+05 1.84094079e+06 7.93761514e+05
 8.20859325e+05 5.04304330e+05 1.10236594e+06 1.10552650e+06
 5.02037759e+05 4.85361989e+05 8.16471018e+05 5.19960796e+05
 6.02639136e+05 5.35912220e+05 6.38985011e+05 1.27380846e+06
 1.11136496e+06 7.74865934e+05 4.69485653e+05 1.61700571e+06
 1.92467480e+06 1.01598312e+06 4.83572472e+05 7.86522067e+05
 1.02802059e+06 7.31570434e+05 5.08760584e+05 6.81584670e+05
 1.28277581e+06 6.56575007e+05 8.50957684e+05 5.01591730e+05
 1.50026465e+06 8.85080337e+05 1.02303449e+06 1.19843507e+06
 1.61457214e+06 5.17969847e+05 7.29328464e+05 8.96559636e+05
 1.35539523e+06 1.09592669e+06 1.02320850e+06 5.47262607e+05
 5.45769844e+05 5.53259285e+05 6.24400006e+05 4.84439803e+05
 6.54555784e+05 1.34041450e+06 1.50900931e+06 1.57970842e+06
 1.27041485e+06 5.08085694e+05 8.69818644e+05 5.63834065e+05
 9.20487258e+05 5.24758769e+05 7.97238162e+05 7.69175002e+05
 3.85649978e+05 1.14854830e+06 2.23644394e+06 3.48894306e+05
 5.37978256e+05 1.11881285e+06 1.25965104e+06 1.61505432e+06
 1.06425091e+06 8.24558541e+05 9.33541548e+05 7.30800224e+05
 5.29986134e+05 1.22183713e+06 9.95710463e+05 1.02671167e+06
 5.26979476e+05 1.24659427e+06 8.44803637e+05 5.28509112e+05
 6.74827357e+05 1.20939127e+06 4.83669593e+05 9.34101519e+05
 1.27603455e+06]

In [66]:

# Create a pipeline with the preprocessor and a RandomForestRegressor model
pipe = Pipeline(steps=[('preprocessor', preprocessor),
                       ('model', RandomForestRegressor(n_estimators=100, random_state=0))])

# Fit the pipeline on the training data
pipe.fit(X_train, y_train)

# Predict on the test data
y_pred = pipe.predict(X_test)

# Display predictions
print("Predicted prices:", y_pred)

NameError: name 'RandomForestRegressor' is not defined